apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: terrafusion-dev
namePrefix: dev-

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- api-gateway-patch.yaml
- sync-service-patch.yaml
- ingress-patch.yaml

secretGenerator:
- name: terrafusion-secrets
  envs:
  - secrets.env

configMapGenerator:
- name: terrafusion-config
  literals:
  - SYNCSERVICE_DEV_MODE=1
  - LOG_LEVEL=DEBUG