apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-service
spec:
  replicas: 2  # Mid-size replica count for staging
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sync-service
              topologyKey: kubernetes.io/hostname
      containers:
      - name: sync-service
        env:
        - name: SYNCSERVICE_DEV_MODE
          valueFrom:
            configMapKeyRef:
              name: stage-terrafusion-config
              key: SYNCSERVICE_DEV_MODE
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: stage-terrafusion-config
              key: LOG_LEVEL
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"