apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api-gateway
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: dev-terrafusion-config
              key: LOG_LEVEL
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"