apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: terrafusion-api-gateway
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
  - port: api-gateway
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: '(api_gateway_.*)'
      action: keep
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: terrafusion-sync-service
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sync-service
  endpoints:
  - port: sync-service
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: '(sync_service_.*)'
      action: keep