apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: terrafusion-prod
namePrefix: prod-

resources:
- ../../base
- namespace.yaml
- persistent-volumes.yaml
- autoscaling.yaml
- network-policies.yaml
- pod-disruption-budgets.yaml

patchesStrategicMerge:
- api-gateway-patch.yaml
- sync-service-patch.yaml
- ingress-patch.yaml

secretGenerator:
- name: terrafusion-secrets
  envs:
  - secrets.env

configMapGenerator:
- name: terrafusion-config
  literals:
  - SYNCSERVICE_DEV_MODE=0
  - LOG_LEVEL=INFO