apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sync-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sync-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: websocket-server-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: websocket-server